project:
  type: website
  output-dir: docs

website:
  title: "daro-training-site"

  sidebar:
    background: "#FECCDD"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://https://github.com/rpowell-fmg/daro-training-site
        text: "GitHub"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - section: "Day 1"
        contents:
          - href: 01_GettingStarted/index.qmd
          - href: 02_DataViz/index.qmd
          - href: 03_TidyData/index.qmd
          - href: 04_SingleDataset/index.qmd
      - section: "Day 2"
        contents:
          - href: 05_JoiningDatasets/index.qmd
          - href: 06_PivotingData/index.qmd
      - section: "Day 3"
        contents:
          - href: 07_ImportExport/index.qmd
          - href: 08_DataAttributes/index.qmd
          - href: 09_LabelledData/index.qmd
      - section: "Day 4"
        contents:


  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025"
    background: "#FFA219"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
    freeze: auto
    echo: true

editor: source